# Install libraries

In [1]:
!pip install opencv-python

# Imports

In [1]:
import cv2
import numpy as np



# Reading image

In [2]:
img_grayscale = cv2.imread('Cat.jpg')


# Displaying an image

In [18]:
print(img_grayscale)

[[[243 243 243]
  [241 241 241]
  [240 240 240]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[242 242 242]
  [240 240 240]
  [239 239 239]
  ...
  [245 245 245]
  [245 245 245]
  [245 245 245]]

 [[241 241 241]
  [239 239 239]
  [238 238 238]
  ...
  [245 245 245]
  [245 245 245]
  [245 245 245]]

 ...

 [[227 233 246]
  [224 230 243]
  [223 229 242]
  ...
  [164 175 189]
  [182 193 207]
  [201 212 226]]

 [[227 233 246]
  [224 230 243]
  [223 229 242]
  ...
  [184 197 213]
  [193 203 220]
  [201 214 230]]

 [[222 230 243]
  [220 228 241]
  [219 227 240]
  ...
  [196 210 229]
  [198 210 228]
  [198 212 230]]]


In [7]:
cv2.imshow('graycsale image',img_grayscale)

In [6]:
cv2.waitKey(0)


-1

In [8]:
cv2.destroyAllWindows()


# Writing an Image

In [19]:
cv2.imwrite('Catcopy.jpg',img_grayscale)


True

In [20]:
img_grayscalecopy = cv2.imread('Catcopy.jpg')

In [21]:
print(img_grayscalecopy)

[[[243 243 243]
  [241 241 241]
  [240 240 240]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[242 242 242]
  [240 240 240]
  [239 239 239]
  ...
  [245 245 245]
  [245 245 245]
  [245 245 245]]

 [[241 241 241]
  [239 239 239]
  [238 238 238]
  ...
  [245 245 245]
  [245 245 245]
  [245 245 245]]

 ...

 [[225 233 246]
  [222 230 243]
  [221 229 242]
  ...
  [163 174 188]
  [183 194 208]
  [199 210 224]]

 [[225 233 246]
  [222 230 243]
  [221 229 242]
  ...
  [184 197 213]
  [193 203 220]
  [201 214 228]]

 [[222 230 243]
  [220 228 241]
  [219 227 240]
  ...
  [196 210 228]
  [198 210 228]
  [198 213 229]]]


# Reading videos

In [4]:
vid_capture = cv2.VideoCapture('Cat.mp4')

In [5]:
#Check if the video was opened successfully
if (vid_capture.isOpened() == False):
  print("Error opening the video file")
else:
  # Get frame rate information
  fps = int(vid_capture.get(5))
  print("Frame Rate : ",fps,"frames per second") 
  # Get frame count
  frame_count = vid_capture.get(7)
  print("Frame count : ", frame_count)


Frame Rate :  25 frames per second
Frame count :  176.0


In [6]:
while(vid_capture.isOpened()):
  # vCapture.read() methods returns a tuple, first element is a bool
  # and the second is frame
 
  ret, frame = vid_capture.read()
  if ret == True:
    cv2.imshow('Frame',frame)
    k = cv2.waitKey(20)
    # 113 is ASCII code for q key
    if k == 113:
      break
  else:
    break


In [7]:
# Release the objects
vid_capture.release()
cv2.destroyAllWindows()


# Reading Video from a Webcam

In [23]:
vid_capture = cv2.VideoCapture(0, cv2.CAP_DSHOW)


In [24]:
# Obtain frame size information using get() method
frame_width = int(vid_capture.get(3))
frame_height = int(vid_capture.get(4))
frame_size = (frame_width,frame_height)
fps = 20

In [25]:
#Initialize video writer object
output = cv2.VideoWriter('Resources/output_video_from_file.avi', cv2.VideoWriter_fourcc('M','J','P','G'), 20, frame_size)

In [26]:
while(vid_capture.isOpened()):
    # vid_capture.read() methods returns a tuple, first element is a bool

    # and the second is frame
    ret, frame = vid_capture.read()
    if ret == True:
           # Write the frame to the output files
        output.write(frame)
    else:
        print('Stream disconnected')
    break

In [27]:
# Release the objects
vid_capture.release()

output.release()

# Image Resizing with OpenCV

In [32]:
# Read the image using imread function
image = cv2.imread('cables.jpg')
cv2.imshow('Original Image', image)

# let's downscale the image using new  width and height
down_width = 300
down_height = 200
down_points = (down_width, down_height)
resized_down = cv2.resize(image, down_points, interpolation= cv2.INTER_LINEAR)
 
# let's upscale the image using new  width and height

up_width = 600
up_height = 400
up_points = (up_width, up_height)
resized_up = cv2.resize(image, up_points, interpolation= cv2.INTER_LINEAR)
 
# Display images

cv2.imshow('Resized Down by defining height and width', resized_down)
cv2.waitKey()
cv2.imshow('Resized Up image by defining height and width', resized_up)
cv2.waitKey()

#press any key to close the windows

cv2.destroyAllWindows()

In [33]:
# Scaling Up the image 1.2 times by specifying both scaling factors
scale_up_x = 1.2
scale_up_y = 1.2

# Scaling Down the image 0.6 times specifying a single scale factor.
scale_down = 0.6

scaled_f_down = cv2.resize(image, None, fx= scale_down, fy= scale_down, interpolation= cv2.INTER_LINEAR)
scaled_f_up = cv2.resize(image, None, fx= scale_up_x, fy= scale_up_y, interpolation= cv2.INTER_LINEAR)
# Display images

cv2.imshow('Resized Down by defining height and width', scaled_f_down)
cv2.waitKey()
cv2.imshow('Resized Up image by defining height and width', scaled_f_up)
cv2.waitKey()

-1

In [34]:
# Scaling Down the image 0.6 times using different Interpolation Method
res_inter_nearest = cv2.resize(image, None, fx= scale_down, fy= scale_down, interpolation= cv2.INTER_NEAREST)
res_inter_linear = cv2.resize(image, None, fx= scale_down, fy= scale_down, interpolation= cv2.INTER_LINEAR)
res_inter_area = cv2.resize(image, None, fx= scale_down, fy= scale_down, interpolation= cv2.INTER_AREA)

In [35]:
# Concatenate images in horizontal axis for comparison

vertical= np.concatenate((res_inter_nearest, res_inter_linear, res_inter_area), axis = 0)
# Display the image Press any key to continue
cv2.imshow('Inter Nearest :: Inter Linear :: Inter Area', vertical)


# Cropping images

In [3]:


img = cv2.imread('cables.jpg')

print(img.shape) # Print image shape

cv2.imshow("original", img)

# Cropping an image
cropped_image = img[80:280, 150:330]
# Display cropped image

cv2.imshow("cropped", cropped_image)

# Save the cropped image

cv2.imwrite("Cropped Image.jpg", cropped_image)

cv2.waitKey(0)

cv2.destroyAllWindows()


(338, 338, 3)


# Image Rotation using OpenCV

In [4]:
# Reading the image
image = cv2.imread('cables.jpg')
#compute the rotation point, which in this example, will be the center of the image.
# Dividing height and width by 2 to get the center of the image
height, width = image.shape[:2]
center = (width/2, height/2)


In [5]:
# the above center is the center of rotation axis
# use cv2.getRotationMatrix2D() to get the rotation matrix
rotate_matrix = cv2.getRotationMatrix2D(center=center, angle=45, scale=1)


In [6]:
# Rotate the image using cv2.warpAffine
rotated_image = cv2.warpAffine(src=image, M=rotate_matrix, dsize=(width, height))

In [7]:
# visualize the original and the rotated image
cv2.imshow('Original image', image)
cv2.imshow('Rotated image', rotated_image)
# wait indefinitely, press any key on keyboard to exit
cv2.waitKey(0)
# write the output, the rotated image to disk
cv2.imwrite('rotated_image.jpg', rotated_image)


True

# Translation of Images using OpenCV

In [10]:
# read the image
image = cv2.imread('cables.jpg')
# get the width and height of the image
height, width = image.shape[:2]

In [11]:
# get tx and ty values for translation
# you can specify any value of your choice
tx, ty = width / 4, height / 4
 
# create the translation matrix using tx and ty, it is a NumPy array
translation_matrix = np.array([ [1, 0, tx],[0, 1, ty]], dtype=np.float32)


In [12]:
# apply the translation to the image
translated_image = cv2.warpAffine(src=image, M=translation_matrix, dsize=(width, height))

In [13]:
# display the original and the Translated images
cv2.imshow('Translated image', translated_image)
cv2.imshow('Original image', image)
cv2.waitKey(0)
# save the translated image to disk
cv2.imwrite('translated_image.jpg', translated_image)


True

# Annotating Images Using OpenCV

In [16]:
# read the image
image = cv2.imread('cables.jpg')
# make a copy of the original image
imageRectangle = img.copy()
# define the starting and end points of the rectangle
start_point =(50,100)
end_point =(75,25)
# draw the rectangle
cv2.rectangle(imageRectangle, start_point, end_point, (0, 0, 255), thickness= 3, lineType=cv2.LINE_8)
# display the output
cv2.imshow('imageRectangle', imageRectangle)
cv2.waitKey(0)


-1

In [19]:
# make a copy of the original image
imageText = img.copy()
#let's write the text you want to put on the image
text = 'These are cables!'
#org: Where you want to put the text
org = (50,350)
# write the text on the input image
cv2.putText(imageText, text, org, fontFace = cv2.FONT_HERSHEY_COMPLEX, fontScale = 1.5, color = (250,225,100))
# display the output image with text over it
cv2.imshow("Image Text",imageText)
cv2.waitKey(0)
cv2.destroyAllWindows()


# Annotating Images Using the Mouse

In [5]:
# Lists to store the bounding box coordinates
top_left_corner=[]
bottom_right_corner=[]
 
# function which will be called on mouse input
def drawRectangle(action, x, y, flags, *userdata):
  # Referencing global variables
  global top_left_corner, bottom_right_corner
  # Mark the top left corner when left mouse button is pressed
  if action == cv2.EVENT_LBUTTONDOWN:
    top_left_corner = [(x,y)]

    # When left mouse button is released, mark bottom right corner
  elif action == cv2.EVENT_LBUTTONUP:

    bottom_right_corner = [(x,y)]   

    # Draw the rectangle
    cv2.rectangle(image, top_left_corner[0], bottom_right_corner[0], (0,255,0),2, 8)

    cv2.imshow("Window",image)
# Read Images

image = cv2.imread("cells.png")

# Make a temporary image, will be useful to clear the drawing

temp = image.copy()

# Create a named window

cv2.namedWindow("Window")

# highgui function called when mouse events occur
cv2.setMouseCallback("Window", drawRectangle)

k=0

# Close the window when key q is pressed

while k!=113:

  # Display the image
  cv2.imshow("Window", image)
  k = cv2.waitKey(0)

  # If c is pressed, clear the window, using the dummy image

  if (k == 99):

    image= temp.copy()

    cv2.imshow("Window", image)

cv2.destroyAllWindows()


# Resizing an Image Using the Trackbar

In [2]:
maxScaleUp = 100
scaleFactor = 1
windowName = "Resize Image"
trackbarValue = "Scale"
# read the image
image = cv2.imread("cells.jpg")

# Create a window to display results and  set the flag to Autosize (WINDOW_AUTOSIZE flag is important because it lets us resize the image)
cv2.namedWindow(windowName, cv2.WINDOW_AUTOSIZE)

# Callback functions (will be called when the user interacts with the trackbar)

def scaleImage(*args):

    # Get the scale factor from the trackbar
    scaleFactor = 1+ args[0]/100.0

    # Resize the image
    scaledImage = cv2.resize(image, None, fx=scaleFactor, fy = scaleFactor, interpolation = cv2.INTER_LINEAR)
    cv2.imshow(windowName, scaledImage)



In [ ]:

# Create trackbar and associate a callback function

cv2.createTrackbar(trackbarValue, windowName, scaleFactor, maxScaleUp, scaleImage)

# Display the image

cv2.imshow(windowName, image)

c = cv2.waitKey(0)

cv2.destroyAllWindows()